### ISSUE TITLE
Playback stops when discord reconnects the gateway

### ISSUE THREAD

**Issue by applebee1558** [Devoxin/Lavalink.py#88] opened 2020-05-15 17:34 UTC
### Summary

When discord sends a reconnect payload and discord.py reconnects with a resume, the playback stops.
### Lavalink & System Version

OS: Windows 10 & Centos 8.1 | Python 3.7.5 | Lavalink.py 3.1.0 |Lavalink latest (3.x)
### Reproduction

Just playing any track or queue for a long time.
Turn on logging for discord.py to info so you can see gateway reconnects
### Expected Results

The audio plays none-stop continuously without problems.
### Actual Results

The audio stops whenever discord.py reconnects to the gateway or when discord sends a reconnect payload and causes the library to reconnect.

### Checklist
- [X] Have you checked that there aren't other open [Bug Reports](../../issues) for the same problem?
- [X] Have you checked that your Lavalink password isn't visible?
- [-] Have you given a traceback if possible?
There is no traceback error, lavalink.py acts like nothing happened, and the server still sends things normally.

**Comment by hamza1311** [comment] 2020-06-26 12:57
I can reproduce this on re`IDENTIFY`s. 

One can reproduce this forcing a "normal" re`IDENTIFY` which can be done by sending a bad payload to the main discord web socket. On receiving that payload, discord will terminate the web socket causing discord.py to invalidate session and `IDENTIFY` again. Once that happens, the lavalink.py's web socket connection to lavalink server will act like a zombie web socket connection causing every request to work properly.

`RESUME`s don't cause zombie web sockets although I have not tested if music playback stops on `RESUME`

**Comment by Devoxin** [comment] 2020-06-26 12:58
Playback stopping on IDENTIFY/disconnect is intentional. Voice connections should be terminated upon shard death.

**Comment by hamza1311** [comment] 2020-06-26 13:19
Still, why does a zombie web socket connection persist after a shard death?

**Comment by Devoxin** [comment] 2020-06-26 21:33
fuck knows, but discord.py's websockets are separate from Lavalink.py's so I would say it's more of a coincidence

**Comment by AndyTempel** [comment] 2020-12-05 13:56
The issue seems to be resolved with the latest d.py updates. Feel free to reopen if it still persists.

**Closed by AndyTempel** 2020-12-05 13:56 UTC
Labels: Discussion needed, bug, help wanted
